# Cloudflare Workers Configuration with Static Assets
# 2025 Modern Configuration for React SPA

name = "mychat"
main = "src/index.js"
compatibility_date = "2025-01-01"  # Use latest compatibility date

# Static Assets Configuration (2025 standard)
[assets]
directory = "./dist"
binding = "ASSETS"
# SPA configuration - serves index.html for unmatched routes
not_found_handling = "single-page-application"

# Observability for debugging
[observability]
enabled = true  # Enable for debugging OAuth issues, disable once stable

# Environment variables
[vars]
# Global variables available in all environments
FRONTEND_URL = "http://localhost:5173"

# OAuth Configuration - Set these as secrets in Cloudflare dashboard:
# GOOGLE_CLIENT_ID = "your-client-id"
# GOOGLE_CLIENT_SECRET = "your-client-secret"  
# JWT_SECRET = "your-jwt-secret"

# Development environment
[env.development.vars]
FRONTEND_URL = "http://localhost:5173"

# Production environment
[env.production.vars]
FRONTEND_URL = "https://mychat.current.space"

# Preview/staging environment
[env.preview.vars]
FRONTEND_URL = "https://preview.mychat.current.space"

# Optional: If you add API routes later
# [assets]
# run_worker_first = ["/api/*"]  # Routes that should invoke Worker first

# Optional: Bindings for Worker functionality
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxxxxxxxxxxxx"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = "xxxxxxxxxxxxx"