# Cloudflare Workers Configuration with Static Assets
# For React SPA with client-side routing

name = "mychat"
compatibility_date = "2025-08-08"

# Static Assets Configuration
[assets]
directory = "./dist"  # Vite build output directory
not_found_handling = "single-page-application"  # Returns index.html for client-side routing

# Environment variables
[vars]
# Global variables available in all environments
FRONTEND_URL = "http://localhost:5173"

# OAuth Configuration - Set these as secrets in Cloudflare dashboard:
# GOOGLE_CLIENT_ID = "your-client-id"
# GOOGLE_CLIENT_SECRET = "your-client-secret"  
# JWT_SECRET = "your-jwt-secret"

[env.production.vars]
# Production-specific variables
FRONTEND_URL = "https://mychat.current.space"

[env.preview.vars]
# Preview/staging variables  
FRONTEND_URL = "https://preview.mychat.current.space"

# Optional: If you add API routes later
# [assets]
# run_worker_first = ["/api/*"]  # Routes that should invoke Worker first

# Optional: Bindings for Worker functionality
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxxxxxxxxxxxx"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = "xxxxxxxxxxxxx"