# Cloudflare Workers Configuration with Static Assets
# 2025 Modern Configuration for React SPA

name = "mychat"
main = "src/index.js"
compatibility_date = "2025-01-01"  # Use latest compatibility date

# Static Assets Configuration (2025 standard)
[assets]
directory = "./dist"
binding = "ASSETS"
# SPA configuration - serves index.html for unmatched routes
not_found_handling = "single-page-application"
# CRITICAL: Run Worker first for API routes (otherwise static assets take precedence)
run_worker_first = ["/api/*"]

# Observability for debugging
[observability]
enabled = true  # Enable for debugging OAuth issues, disable once stable

# Environment variables
[vars]
# Default variables (overridden by environment-specific vars)
FRONTEND_URL = "https://mychat.current.space"

# OAuth Configuration - Set these as secrets in Cloudflare dashboard:
# GOOGLE_CLIENT_ID = "your-client-id"
# GOOGLE_CLIENT_SECRET = "your-client-secret"  
# JWT_SECRET = "your-jwt-secret"

# AI Provider Configuration - Set these as secrets:
# OPENAI_API_KEY = "sk-..."
# OPENAI_MODEL = "gpt-4-turbo-preview"
# ANTHROPIC_API_KEY = "sk-ant-..."
# ANTHROPIC_MODEL = "claude-3-opus-20240229"

# Development environment
[env.development.vars]
FRONTEND_URL = "http://localhost:5173"

# Production environment
[env.production.vars]
FRONTEND_URL = "https://mychat.current.space"

# Preview/staging environment
[env.preview.vars]
FRONTEND_URL = "https://preview.mychat.current.space"


# Optional: KV namespace for chat history
# Create with: wrangler kv:namespace create CHAT_HISTORY
# [[kv_namespaces]]
# binding = "CHAT_HISTORY"
# id = "your-kv-namespace-id"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = "xxxxxxxxxxxxx"