# Cloudflare Workers Configuration with Static Assets
# For React SPA with client-side routing

name = "mychat"
compatibility_date = "2024-09-19"

# Static Assets Configuration
[assets]
directory = "./dist"  # Vite build output directory
not_found_handling = "single-page-application"  # Returns index.html for client-side routing

# Environment variables
[vars]
# Global variables available in all environments
# API_URL = "https://api.example.com"

[env.production.vars]
# Production-specific variables
# NODE_ENV = "production"

[env.preview.vars]
# Preview/staging variables  
# NODE_ENV = "preview"
# DEBUG = "true"

# Optional: If you add API routes later
# [assets]
# run_worker_first = ["/api/*"]  # Routes that should invoke Worker first

# Optional: Bindings for Worker functionality
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxxxxxxxxxxxx"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = "xxxxxxxxxxxxx"